on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  called_workflow:
    runs-on: ubuntu-latest
    steps:
    - run: echo hello
