on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      envPAT:
        required: false

jobs:
  called_workflow:
    runs-on: ubuntu-latest
    steps:
    - run: echo 'i was called.'
